In [1]:
import json
import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy import (
    Column,
    Integer,
    String,
    DateTime,
    Boolean,
    BigInteger,
    ForeignKey,
)
from sqlalchemy.orm import DeclarativeBase

In [2]:
path = "C:/Users/Andrea/Desktop/Spotify Data/Spotify Extended Streaming History/Streaming_History_Audio_2015-2016_0.json"
with open(path, "r", encoding="utf-8") as f:
    data = json.load(f)

print(type(data))
print(len(data))
print(data[0])

<class 'list'>
15646
{'ts': '2015-01-04T00:25:14Z', 'platform': 'iOS 8.1.2 (iPhone4,1)', 'ms_played': 190960, 'conn_country': 'IT', 'ip_addr': '151.48.146.65', 'master_metadata_track_name': 'Kingston Town', 'master_metadata_album_artist_name': 'Alborosie', 'master_metadata_album_album_name': 'Escape From Babylon To The Kingdom Of Zion', 'spotify_track_uri': 'spotify:track:6cOrnBtY3jN76BQpYTiD8v', 'episode_name': None, 'episode_show_name': None, 'spotify_episode_uri': None, 'audiobook_title': None, 'audiobook_uri': None, 'audiobook_chapter_uri': None, 'audiobook_chapter_title': None, 'reason_start': 'clickrow', 'reason_end': 'trackdone', 'shuffle': False, 'skipped': False, 'offline': False, 'offline_timestamp': None, 'incognito_mode': False}

In [3]:
df = pd.DataFrame(data)

## Artist table

In [4]:
artists = (
    df[["master_metadata_album_artist_name"]]
    .dropna()
    .drop_duplicates()
    .reset_index(drop=True)
    .rename(columns={
        "master_metadata_album_artist_name": "name"
    })
)

artists.insert(0, "artist_id", range(1, len(artists) + 1))

artists

     artist_id                 name
0            1            Alborosie
1            2          Eek-A-Mouse
2            3             Skálmöld
3            4  my bloody valentine
4            5        Damian Marley
..         ...                  ...
879        880               Jovine
880        881               Brusco
881        882               Senbeï
882        883           Glesbygd'n
883        884           Uwe Banton

[884 rows x 2 columns]

## Album table

In [5]:
artist_id_map = artists.set_index("name")["artist_id"]

albums = (
    df[
        [
            "master_metadata_album_artist_name",
            "master_metadata_album_album_name",
        ]
    ]
    .dropna()
    .drop_duplicates()
    .rename(columns={
        "master_metadata_album_artist_name": "artist_name",
        "master_metadata_album_album_name": "name"
    })
)

albums["artist_id"] = albums["artist_name"].map(artist_id_map)

albums = albums[
    ["artist_id", "name"]
].reset_index(drop=True)

albums.insert(0, "album_id", range(1, len(albums) + 1))

albums

      album_id  artist_id                                        name
0            1          1  Escape From Babylon To The Kingdom Of Zion
1            2          1                            Rastafari Anthem
2            3          1                            Sound The System
3            4          2                The Very Best Of Eek-A-Mouse
4            5          3                                  Með vættum
...        ...        ...                                         ...
1423      1424        378                        Bring Back the Vibes
1424      1425        378                              Heartical Soul
1425      1426        882                                  Army of Me
1426      1427        883            En Hand Som Värjer Kronans Tyngd
1427      1428        884                              Rightful Place

[1428 rows x 3 columns]

## Song table

In [6]:
# Create a mapping from (artist_id, album_name) to album_id
album_id_map = (
    albums
    .set_index(["artist_id", "name"])["album_id"]
)

# Extract unique songs from the streaming history
songs = (
    df[
        [
            "spotify_track_uri",
            "master_metadata_track_name",
            "master_metadata_album_album_name",
            "master_metadata_album_artist_name",
        ]
    ]
    .dropna(subset=["spotify_track_uri"])
    .drop_duplicates("spotify_track_uri")
    .rename(columns={
        "master_metadata_track_name": "name",
        "master_metadata_album_album_name": "album_name",
        "master_metadata_album_artist_name": "artist_name",
    })
)

# Get the artist_id for each song
artist_id_map = artists.set_index("name")["artist_id"]
songs["artist_id"] = songs["artist_name"].map(artist_id_map)

# Get the album_id using artist + album
songs["album_id"] = songs.set_index(
    ["artist_id", "album_name"]
).index.map(album_id_map)

# Keep only the columns belonging to the song table
songs = songs[
    [
        "name",
        "album_id",
        "spotify_track_uri",
    ]
].reset_index(drop=True)

# Create an explicit primary key
songs.insert(0, "song_id", range(1, len(songs) + 1))

songs

,song_id,name,album_id,spotify_track_uri
0,1,Kingston Town,1,spotify:track:6cOrnBtY3jN76BQpYTiD8v
1,2,Rastafari Anthem,2,spotify:track:7CrAKyg7NuhfSI7LtvePWa
2,3,Rock The Dancehall,3,spotify:track:2dePsNPukZ3fqikLNieXvk
3,4,Play Fool [To Catch Wise],3,spotify:track:5dbVRCh0tXEIRJWSI0uen1
4,5,Real Story,1,spotify:track:09lCCz4rOMk1dGGOWeKZ7s
...,...,...,...,...
3453,3454,Human Race,1106,spotify:track:1IKKZJovte5PkKt4aCzNLY
3454,3455,Intro,1425,spotify:track:0q7YD2j9OAiejy97KdfjzE
3455,3456,Rules of Babylon,1425,spotify:track:0fRFziM4ttj4ShivjRqd8L
3456,3457,Ruff Inna Town,1425,spotify:track:6HIBpl4Mi3ni1SD8zpNJeC
3457,3458,Can't Stand It - feat. Dennis Brown,1,spotify:track:4CROyxtk7tbwP3fZICrEI6

## User table

In [7]:
users = pd.DataFrame({
    "user_id": [1],
    "username": ["Andrea"]
})

users

   user_id username
0        1   Andrea

## Platform table

In [8]:
platforms = (
    df[["platform"]]
    .dropna()
    .drop_duplicates()
    .reset_index(drop=True)
)

platforms.insert(0, "platform_id", range(1, len(platforms) + 1))

platforms.insert(1, "user_id", 1)

platforms

   platform_id  user_id                           platform
0            1        1              iOS 8.1.2 (iPhone4,1)
1            2        1              iOS 8.1.3 (iPhone4,1)
2            3        1  Windows 7 (6.1.7601; x64; SP1; S)
3            4        1                iOS 8.3 (iPhone4,1)
4            5        1              iOS 8.4.1 (iPhone4,1)

## Listen table

In [9]:
listens = df[
    [
        "ts",
        "platform",
        "spotify_track_uri",
        "ms_played",
        "conn_country",
        "ip_addr",
        "reason_start",
        "reason_end",
        "shuffle",
        "skipped",
        "offline",
        "offline_timestamp",
        "incognito_mode",
    ]
].copy()

platform_id_map = platforms.set_index("platform")["platform_id"]
song_id_map = songs.set_index("spotify_track_uri")["song_id"]

listens["platform_id"] = listens["platform"].map(platform_id_map)
listens["song_id"] = listens["spotify_track_uri"].map(song_id_map)

listens = listens[
    [
        "song_id",
        "platform_id",
        "ts",
        "ms_played",
        "conn_country",
        "ip_addr",
        "reason_start",
        "reason_end",
        "shuffle",
        "skipped",
        "offline",
        "offline_timestamp",
        "incognito_mode",
    ]
].reset_index(drop=True)

listens.insert(0, "listen_id", range(1, len(listens) + 1))

listens["ts"] = pd.to_datetime(listens["ts"], utc=True)

listens

,listen_id,song_id,platform_id,ts,ms_played,conn_country,ip_addr,reason_start,reason_end,shuffle,skipped,offline,offline_timestamp,incognito_mode
0,1,1,1,2015-01-04 00:25:14+00:00,190960,IT,151.48.146.65,clickrow,trackdone,False,False,False,None,False
1,2,2,1,2015-01-04 00:28:37+00:00,203493,IT,151.48.146.65,trackdone,trackdone,True,False,False,None,False
2,3,3,1,2015-01-04 00:32:27+00:00,229066,IT,151.48.146.65,trackdone,trackdone,True,False,False,None,False
3,4,4,1,2015-01-04 00:36:28+00:00,240893,IT,151.48.146.65,trackdone,trackdone,True,False,False,None,False
4,5,5,1,2015-01-04 00:39:47+00:00,198146,IT,151.48.146.65,trackdone,trackdone,True,False,False,None,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15641,15642,1608,3,2016-01-13 17:32:55+00:00,255744,IT,151.48.148.126,trackdone,trackdone,False,False,False,None,False
15642,15643,1658,3,2016-01-13 17:36:03+00:00,187849,IT,151.48.148.126,trackdone,trackdone,False,False,False,None,False
15643,15644,1682,3,2016-01-13 17:40:05+00:00,241746,IT,151.48.148.126,trackdone,trackdone,False,True,False,None,False
15644,15645,1545,3,2016-01-13 17:43:57+00:00,170086,IT,151.48.148.126,trackdone,trackdone,False,False,False,None,False
15645,15646,1674,3,2016-01-13 17:48:24+00:00,267679,IT,151.48.148.126,trackdone,trackdone,False,False,False,None,False

## Upload tables to database

In [10]:
# Create an engine
engine = create_engine("mysql+pymysql://root:root@localhost/")

with engine.connect() as connection:
    connection.execute(text("CREATE DATABASE IF NOT EXISTS spotify_db"))

In [11]:
engine = create_engine(
    "mysql+pymysql://root:root@localhost/spotify_db"
)

In [12]:
class Base(DeclarativeBase):
    pass


class User(Base):
    __tablename__ = "users"

    user_id = Column(Integer, primary_key=True)
    username = Column(String(100), nullable=False)


class Artist(Base):
    __tablename__ = "artists"

    artist_id = Column(Integer, primary_key=True)
    name = Column(String(255), nullable=False)


class Album(Base):
    __tablename__ = "albums"

    album_id = Column(Integer, primary_key=True)
    artist_id = Column(Integer, ForeignKey("artists.artist_id"), nullable=False)
    name = Column(String(255), nullable=False)


class Song(Base):
    __tablename__ = "songs"

    song_id = Column(Integer, primary_key=True)
    album_id = Column(Integer, ForeignKey("albums.album_id"), nullable=False)
    name = Column(String(255), nullable=False)
    spotify_track_uri = Column(String(100), nullable=False)


class Platform(Base):
    __tablename__ = "platforms"

    platform_id = Column(Integer, primary_key=True)
    user_id = Column(Integer, ForeignKey("users.user_id"), nullable=False)
    platform = Column(String(255), nullable=False)


class Listen(Base):
    __tablename__ = "listens"

    listen_id = Column(Integer, primary_key=True)
    song_id = Column(Integer, ForeignKey("songs.song_id"), nullable=False)
    platform_id = Column(Integer, ForeignKey("platforms.platform_id"), nullable=False)

    ts = Column(DateTime, nullable=False)
    ms_played = Column(Integer)
    conn_country = Column(String(2))
    ip_addr = Column(String(45))
    reason_start = Column(String(50))
    reason_end = Column(String(50))
    shuffle = Column(Boolean)
    skipped = Column(Boolean)
    offline = Column(Boolean)
    offline_timestamp = Column(BigInteger)
    incognito_mode = Column(Boolean)

In [13]:
Base.metadata.create_all(engine)

In [14]:
users.to_sql(
    "users",
    engine,
    if_exists="append",
    index=False,
)

artists.to_sql(
    "artists",
    engine,
    if_exists="append",
    index=False,
)

albums.to_sql(
    "albums",
    engine,
    if_exists="append",
    index=False,
)

songs.to_sql(
    "songs",
    engine,
    if_exists="append",
    index=False,
)

platforms.to_sql(
    "platforms",
    engine,
    if_exists="append",
    index=False,
)

listens.to_sql(
    "listens",
    engine,
    if_exists="append",
    index=False,
)

15646